name: deploy google app engine
on: 
  push:
    branches: [master]

jobs:
  deploy_source:
    name: auto ssh to server and run it
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: create .env file
        run: |
          echo "$PROD_ENV_FILE" > .env
          echo "$GOOGLE_CLOUD_KEY_DATA" > google-key.json
        env:
          PROD_ENV_FILE: '${{secrets.PRODUCTION_ENV}}'
          GOOGLE_CLOUD_KEY_DATA: '${{secrets.GOOGLE_CLOUD_KEY}}'
      - name: 🔨 Build Project
        run: |
          npm install
          npm run build
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ./dist/
          log-level: verbose
          dangerous-clean-slate: true
          dry-run: true

