name: deploy google app engine
on: 
  push:
    branches: [master]

jobs:
  deploy_source:
    name: Deploying to server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Create .env file
        run: |
          echo "$PROD_ENV_FILE" > .env
          echo "$GOOGLE_CLOUD_KEY_DATA" > google-key.json
        env:
          PROD_ENV_FILE: '${{secrets.PRODUCTION_ENV}}'
          GOOGLE_CLOUD_KEY_DATA: '${{secrets.GOOGLE_CLOUD_KEY}}'
      - name: Build Project
        run: |
          npm install
          npm run build
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ./dist/
          log-level: verbose
          dangerous-clean-slate: true
      - name: SSH to server and run script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            source /home/experime/nodevenv/public_html/api/16/bin/activate && cd /home/experime/public_html/api
            cd /home/experime/public_html/api
            yarn install --production
            npm run stop
            npm run start
            exit
