name: deploy to lambda
on: [push]
jobs:
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          yarn add --dev typescript
          npm run build 
        env:
          CI: true
      - name: npm install on dist folder, create .env file, and deploy serverless
        run: |
          cd dist
          yarn install --frozen-lockfile --production
          echo "$PROD_ENV_FILE" > .env
          npm run deploy
        env:
          PROD_ENV_FILE: ${{ secrets.PRODUCTION_DATABASE_ENV }}

