name: deploy google app engine
on: [push]
jobs:
  deploy_source:
    name: build and deploy google app engine
    strategy:
      matrix:
        node-version: [14.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{secrets.GCP_SA_KEY}}'
      - name: create .env file
        run: |
          echo "$PROD_ENV_FILE" > .env
          echo "$GOOGLE_CLOUD_KEY_DATA" > google-key.json
          echo "$PROD_ENV_FILE"
          ls -la
          cat .env
        env:
          PROD_ENV_FILE: '${{secrets.PRODUCTION_ENV}}'
          GOOGLE_CLOUD_KEY_DATA: '${{secrets.GOOGLE_CLOUD_KEY}}'
      - id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v0'

